name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
        - ubuntu-latest
        # - macos-latest
        # - windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install Alsa lib
        if: "runner.os == 'Linux'"
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Move Files
        shell: bash
        run: ./scripts/move_dist.sh

      - name: Upload Linux Artifacts
        if: "runner.os == 'Linux'"
        uses: actions/upload-artifact@v1
        with:
          name: soundsync-linux
          path: dist-linux

      - name: Upload Mac Artifacts
        if: "runner.os == 'macOS'"
        uses: actions/upload-artifact@v1
        with:
          name: soundsync-mac
          path: dist-mac

      - name: Upload Win Artifacts
        if: "runner.os == 'Windows'"
        uses: actions/upload-artifact@v1
        with:
          name: soundsync-win
          path: dist-win
